# Netlify configuration file

# This rule proxies requests from your app's /api/ path
# to the live AEMO GBB API server, solving the CORS issue.
[[redirects]]
  from = "/api/*"
  to = "https://gbbwa.aemo.com.au/api/v1/:splat"
  status = 200
  force = true

# This new rule proxies requests from /bom-api/ path
# to the live BOM weather data server.
[[redirects]]
  from = "/bom-api/*"
  to = "http://www.bom.gov.au/:splat"
  status = 200
  force = true
