# Netlify configuration file

# This rule proxies all AEMO API requests
# from: /api/*
# to:   https://gbbwa.aemo.com.au/api/v1/*
[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://gbbwa.aemo.com.au/api/v1/:splat"
  status = 200
  force = true
