# Netlify configuration file

# This rule proxies requests from your app's /api/ path
# to the live AEMO GBB API server, solving the CORS issue.
[[redirects]]
  from = "/api/*"
  to = "https://gbbwa.aemo.com.au/api/v1/:splat"
  status = 200
  force = true

# This new rule proxies requests from /bom-api/ path
# to the live BOM weather data server using a secure connection.
[[redirects]]
  from = "/bom-api/*"
  to = "https://www.bom.gov.au/:splat" # CORRECTED: Changed http to https
  status = 200
  force = true
