# Netlify configuration file

# This rule proxies requests from your app's /api/ path
# to the live AEMO GBB API server, solving the CORS issue.
[[redirects]]
  from = "/api/*"
  to = "https://gbbwa.aemo.com.au/api/v1/:splat"
  status = 200
  force = true
